//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CSTester.rc
//
#define IDOK2                           2
#define IDC_BN_NEXT                     3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CSTESTER_DIALOG             102
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_DLG_BOM                     130
#define IDD_DLG_AGM                     131
#define IDD_DLG_AGM1                    131
#define IDD_DLG_TVM                     132
#define IDD_DLG_TCM                     133
#define IDD_DLG_OPER                    134
#define IDD_DLG_LOGIN                   135
#define IDD_DLG_DECR                    137
#define IDD_DLG_INCR                    138
#define IDD_DLG_SJTSALE                 139
#define IDD_DLG_REFUND                  140
#define IDD_DLG_UPDATE                  141
#define IDD_DLG_PRICE                   145
#define IDD_DLG_PARAM                   146
#define IDB_BMP_ABOUT                   149
#define IDB_BMP_AGM                     150
#define IDB_BMP_BOM                     151
#define IDB_BMP_TCM                     152
#define IDB_BMP_TVM                     153
#define IDB_BMP_FZONE                   157
#define IDB_BMP_PZONE                   158
#define IDD_DLG_INCR1                   167
#define IDD_DLG_SAM_ACT                 167
#define IDD_DLG_CMD                     168
#define IDD_DLG_TEST_HARD               175
#define IDD_DLG_DESCIND                 176
#define IDD_DLG_DEBUG                   177
#define IDD_DLG_CONFIRM                 178
#define IDD_DLG_GET_FILE                179
#define IDD_DIALOG1                     180
#define IDD_DLG_DEGRADE                 181
#define IDD_DLG_SALE_EX                 182
#define IDD_ESINIT                      183
#define IDC_REDIT_OUT                   1000
#define IDC_BN_DEFFER                   1003
#define IDC_COMB_ANT                    1004
#define IDC_BN_INC                      1004
#define IDC_BN_SALE                     1005
#define IDC_COMB_PORT                   1005
#define IDC_BN_REFUND                   1006
#define IDC_BN_ACTIVE                   1007
#define IDC_BN_UNLOCK                   1008
#define IDC_BN_CLEAR                    1009
#define IDC_BN_UPDATE                   1010
#define IDC_BN_SVT_INC                  1011
#define IDC_BN_CLEAR2                   1011
#define IDC_BN_FATV                     1011
#define IDC_BN_CLEAR_SJT                1012
#define IDC_EDT_STATION                 1013
#define IDC_BN_CLEAR_SJT2               1013
#define IDC_BN_SALE_ON                  1013
#define IDC_EDT_DEVICE                  1014
#define IDC_BN_SALE_ON2                 1014
#define IDC_BN_INIT                     1015
#define IDC_BN_LOGIN                    1016
#define IDC_BN_INIT2                    1016
#define IDC_BN_AGM_OPEN                 1016
#define IDC_BN_DEV_INIT                 1016
#define IDC_BN_SALE_ON3                 1016
#define IDC_BN_ANALYSE                  1017
#define IDC_BN_SALE_EXIT                1018
#define ES_BN_ANALYSE                   1018
#define IDC_BN_SALE_ON4                 1018
#define IDC_BN_SALE_SJT                 1019
#define ES_BN_INIT                      1019
#define IDC_BN_HISTORY                  1020
#define IDC_BN_READ                     1020
#define ES_BN_EVALUATE                  1020
#define IDC_BN_SALE_ON5                 1020
#define IDC_BN_SVT_DEC                  1021
#define IDC_BN_DESCIND                  1021
#define ES_BN_DESTROY                   1021
#define IDC_BN_DESTORY                  1022
#define ES_BN_RECODE                    1022
#define IDC_BN_SALE_ON6                 1022
#define IDC_BN_ENTRY                    1023
#define IDC_BN_OPEN                     1023
#define IDC_BN_EXIT                     1024
#define IDC_BN_CLOSE                    1024
#define IDC_BN_TKINFO                   1025
#define IDC_EDIT_OPERID                 1026
#define ES_BN_PRIVATE                   1026
#define IDC_EDIT_PWD                    1027
#define IDC_BN_CANCEL                   1028
#define IDC_EDIT_BEFORE                 1029
#define IDC_EDIT_AFTER                  1031
#define IDC_EDIT_TODECR                 1032
#define IDC_EDIT_AMOUNT                 1032
#define IDC_BN_DECREASE                 1033
#define IDC_COMB_FARE                   1034
#define IDC_COMB_FARE2                  1035
#define IDC_COMB_STATION                1035
#define IDC_COMB_PAY_TYPE               1035
#define IDC_EDIT2                       1036
#define IDC_EDIT_VALUE                  1036
#define IDC_BN_INCREASE                 1037
#define IDC_EDIT_VALUE3                 1037
#define IDC_RADIO1                      1038
#define IDC_BN_CFG                      1038
#define IDC_RADIO2                      1039
#define IDC_BN_CFG2                     1039
#define IDC_RADIO3                      1040
#define IDC_RADIO_AISLE2                1041
#define IDC_EDIT_TOINCR                 1042
#define IDC_RADIO_AISLE3                1042
#define IDC_EDIT_PORT                   1043
#define IDC_STATIC_ZONE                 1045
#define IDC_EDIT_STATION                1047
#define IDC_EDIT_DEVICE                 1048
#define IDC_COMB_UPD_TYPE               1050
#define IDC_COMB_ENTRY_LINE             1051
#define IDC_COMB_UPD_TYPE3              1052
#define IDC_COMB_ENTRY_STATION          1052
#define IDC_COMB_SATTION                1054
#define IDC_COMB_TYPE                   1055
#define IDC_EDIT_UNION                  1056
#define IDC_BN_QUERY                    1057
#define IDC_BN_CUR                      1058
#define IDC_BN_STATION                  1059
#define IDC_RADIO_AISLE1                1060
#define IDC_BN_SAM_ACTV                 1063
#define IDC_BN_CHARGE                   1064
#define IDC_PROGRESS_SEND               1065
#define IDC_STATIC_RATE                 1066
#define IDC_CMB_DEV_TYPE                1068
#define IDC_CMB_ASYLE_TYPE2             1069
#define IDC_IPADDR_SERVER               1069
#define IDC_CMB_ANT_TYPE                1069
#define IDC_CMB_ASYLE_TYPE              1069
#define IDC_BN_TESTKK                   1070
#define IDC_CMB_ANT                     1070
#define IDC_BN_TEST                     1071
#define IDC_COMB_BEEP                   1072
#define IDC_CMB_PORT                    1072
#define IDC_CMB_SAM_SOCK                1073
#define IDC_RICHEDIT21                  1074
#define IDC_CMB_SAM_BAUD                1075
#define IDC_BN_RF_VER                   1076
#define IDC_EDIT1                       1077
#define IDC_BN_REFRESH                  1078
#define IDC_EDIT_TIME                   1078
#define IDC_STATIC_LEN                  1079
#define IDC_BN_MInit                    1080
#define IDC_BN_MREQ                     1081
#define IDC_BN_MATC                     1082
#define IDC_BN_MSel                     1083
#define IDC_BN_MREAD                    1084
#define IDC_BN_MWRITE                   1085
#define IDC_BN_MAUTH                    1086
#define IDC_BN_UL_REQ                   1087
#define IDC_BN_UL_ANTC                  1088
#define IDC_BN_UL_SEL                   1089
#define IDC_BN_UL_READ                  1090
#define IDC_BN_UL_WRITE                 1091
#define IDC_BN_UL_CWRITE                1092
#define IDC_BN_CPU_RST                  1093
#define IDC_BN_CPU_CMD                  1094
#define IDC_BN_UL_ANTC2                 1095
#define IDC_BN_SAM_BAUD                 1096
#define IDC_BN_SAM_RST                  1097
#define IDC_BN_SAM_CMD                  1098
#define IDC_CMB_KEY                     1099
#define IDC_CMB_LINE                    1100
#define IDC_BN_UL_SEL2                  1101
#define IDC_CHK_SAM1                    1102
#define IDC_BN_LOAD                     1102
#define IDC_CHK_SAM5                    1103
#define IDC_CHK_SAM2                    1104
#define IDC_CHK_SAM6                    1105
#define IDC_CHK_SAM3                    1106
#define IDC_CHK_SAM7                    1107
#define IDC_CHECK7                      1108
#define IDC_CHK_SAM8                    1108
#define IDC_CHK_SAM4                    1109
#define IDC_CHECK9                      1110
#define IDC_CHK_MAIN                    1110
#define IDC_CHECK10                     1111
#define IDC_CHK_SUB                     1111
#define IDC_BN_START                    1112
#define IDC_COMB_MAIN_TYPE              1114
#define IDC_COMB_SUB_TYPE               1115
#define IDC_COMB_SER                    1116
#define IDC_REDIT_RESULT                1117
#define IDC_COMB_CMD                    1118
#define IDC_COMB_BAUD                   1118
#define IDC_EDIT_LGCID                  1119
#define IDC_EDIT_BALANCE                1120
#define IDC_EDIT_CLASSIC                1121
#define IDC_EDIT_ADDR                   1122
#define IDC_EDIT_DATA                   1123
#define IDC_BN_SEND                     1124
#define IDC_CHECK1                      1125
#define IDC_CHK_FORBBID                 1125
#define IDB_CONFIRM                     1126
#define IDB_UNLOCK_SCREEN               1127
#define IDC_EDIT_SHARE_NAME             1128
#define IDC_EDIT_SAVE_FOLDER            1129
#define IDC_EDIT_SHARE_NAME2            1129
#define ID_GET                          1130
#define IDC_EDIT_SHARE_NAME3            1130
#define IDC_STATIC_NOTICE               1131
#define IDC_EDIT_SHARE_NAME4            1131
#define IDC_EDIT_PSW                    1132
#define IDC_EDIT_SHARE_NAME5            1132
#define IDC_MODE_TYPE                   1133
#define IDC_EDIT_SHARE_NAME6            1133
#define IDC_DP_DATE                     1134
#define IDC_EDIT_SHARE_NAME7            1134
#define IDC_EDIT_SHARE_NAME8            1135
#define IDC_MODE_STATION                1136
#define IDC_EDIT_SHARE_NAME9            1136
#define IDC_MODE_FLAG                   1137
#define IDC_EDIT_SHARE_NAME10           1137
#define IDC_BN_SET                      1138
#define IDC_EDIT_SHARE_NAME11           1138
#define IDC_BN_TAC                      1139
#define IDC_EDIT_SHARE_NAME12           1139
#define IDC_EDIT_PENALTY                1140
#define IDC_EDIT_SHARE_NAME13           1140
#define IDC_COMB_CODE                   1141
#define IDC_EDIT_SHARE_NAME14           1141
#define IDC_EDIT_SHARE_NAME15           1142
#define IDC_EDIT_SHARE_NAME16           1143
#define IDC_EDIT_SHARE_NAME17           1160
#define IDC_EDIT_SHARE_NAME18           1161
#define IDC_EDIT_SHARE_NAME19           1162
#define IDC_EDIT_SHARE_NAME20           1163
#define IDC_EDIT_SHARE_NAME21           1164
#define IDC_EDIT_SHARE_NAME22           1165
#define IDC_EDIT_SHARE_NAME23           1166
#define IDC_EDIT_SHARE_NAME24           1167
#define IDC_EDIT_SHARE_NAME25           1168
#define IDC_EDIT_SHARE_NAME26           1169
#define IDC_EDIT_SHARE_NAME27           1170
#define IDC_EDIT_SHARE_NAME28           1171
#define IDC_EDIT_SHARE_NAME29           1172
#define IDC_EDIT_SHARE_NAME30           1173
#define IDC_EDIT_SHARE_NAME31           1174
#define IDC_EDIT_SHARE_NAME32           1175
#define IDC_EDIT_SHARE_NAME33           1176
#define IDC_EDIT_SHARE_NAME34           1177
#define IDC_EDIT_SHARE_NAME35           1178
#define IDC_EDIT_SHARE_NAME36           1179
#define IDC_EDIT_SHARE_NAME37           1180
#define IDC_EDIT_SHARE_NAME38           1181
#define IDC_EDIT_SHARE_NAME39           1182
#define IDC_EDIT_SHARE_NAME40           1183
#define IDC_EDIT_SHARE_NAME41           1184
#define IDC_EDIT_SHARE_NAME42           1185
#define IDC_EDIT_VALUE2                 1186
#define IDC_BN_SALE_SJT2                1187
#define IDM_EXIT                        32771
#define IDM_SAVE_DISP                   32772
#define IDM_CLEAR_DISP                  32773
#define IDM_DEV_BOM                     32774
#define IDM_DEV_AGM                     32775
#define IDM_DEV_TVM                     32776
#define IDM_DEV_TCM                     32777
#define IDM_SEP                         32778
#define IDM_DEV_AVM                     32779
#define IDM_QUERY_FARE                  32813
#define IDM_CUR_PARAMS                  32814
#define ID_Menu                         32815
#define IDM_PARAM                       32820
#define ID_SAM32829                     32829
#define ID_SAM_INFO                     32830
#define IDM_CMD                         32831
#define ULTRALIGHT                      32832
#define IDM_TEST_HARD                   32839
#define IDM_READER_VERSION              32840
#define IDM_TRADE_FILE_EXCH             32841
#define IDM_DEBUG                       32843
#define IDM_UPGRADE                     32844
#define IDM_GETFILE                     32846
#define IDM_ENALBE_DEBUGER              32848
#define ID_32849                        32849
#define IDM_SET_DEGRADE                 32850
#define IDT_BOM                         35003
#define IDT_AGM                         35004
#define IDT_TVM                         35005
#define IDT_TCM                         35006
#define IDT_ABOUT                       35007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32851
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
